version: "3.9"

services:
  web:
    image: maricm123/heartapp:latest
    command: >
      uvicorn django_heart.asgi:application
      --host 0.0.0.0
      --port 8000
      --workers 2
      --ws-ping-interval 20
      --ws-ping-timeout 30
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:15
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    restart: always

  # celery:
  #   image: maricm123/heartapp:latest
  #   command: celery -A django_heart worker -l info --concurrency=4
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   restart: always

  # celery-beat:
  #   image: maricm123/heartapp:latest
  #   command: celery -A django_heart beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   restart: always

volumes:
  postgres_data: