# Generated by Django 4.2.29 on 2026-03-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0009_trainingsession_paused_at_and_more'),
        ('user', '0012_deleteuserprofileconfirmation_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTrainingSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creations')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('ai_prompt', models.TextField(help_text='AI prompt used to generate content')),
                ('generated_content', models.TextField(help_text='Generated email content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_training_session_reports', to='user.coach')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_training_session_reports', to='training_session.trainingsession')),
            ],
            options={
                'verbose_name': 'Email Training Session Report',
                'verbose_name_plural': 'Email Training Session Reports',
            },
        ),
    ]
