# Generated by Django 4.2.29 on 2026-03-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailtrainingsessionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtrainingsessionreport',
            name='tenant_schema_name',
            field=models.CharField(default='public', max_length=100),
        ),
    ]
