# Generated by Django 4.2.23 on 2025-08-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='user',
        ),
    ]
