# Generated by Django 4.2.23 on 2025-08-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('training_session', '0002_remove_trainingsession_user'),
        ('user', '0003_remove_user_gender_remove_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.client'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.coach'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='gym',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='gym.gymtenant'),
            preserve_default=False,
        ),
    ]
