# Generated by Django 4.2.23 on 2025-10-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0003_trainingsession_client_trainingsession_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='duration_in_minutes',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
