# Generated by Django 4.2.23 on 2025-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0004_remove_trainingsession_duration_in_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='calories_burned',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatic calculated', max_digits=8, null=True),
        ),
    ]
