# Generated by Django 4.2.23 on 2025-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0005_alter_trainingsession_calories_burned'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='average_bpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_bpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='min_bpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
