# Generated by Django 4.2.23 on 2025-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0006_trainingsession_average_bpm_trainingsession_max_bpm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='average_bpm',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='max_bpm',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='min_bpm',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='summary_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
