# Generated by Django 5.0.1 on 2025-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0007_remove_trainingsession_average_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
