# Generated by Django 5.2.9 on 2026-01-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0008_trainingsession_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
