# Generated by Django 4.2.23 on 2025-08-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_gymmanager'),
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartraterecord',
            name='user',
        ),
        migrations.AddField(
            model_name='heartraterecord',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.client'),
            preserve_default=False,
        ),
    ]
