# Generated by Django 4.2.23 on 2025-10-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_remove_heartraterecord_user_heartraterecord_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartraterecord',
            name='session_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='heartraterecord',
            index=models.Index(fields=['training_session', 'timestamp'], name='heart_heart_trainin_0bb231_idx'),
        ),
    ]
