# Generated by Django 4.2.23 on 2025-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='max_heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
