# Generated by Django 5.0.1 on 2025-11-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in centimeters (cm)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kilograms (kg)', max_digits=5, null=True),
        ),
    ]
