# Generated by Django 5.0.1 on 2025-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_client_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auto_calculate_max_hr',
            field=models.BooleanField(default=False, help_text='Coach choose an option, will max heart rate being calculated based on client age'),
        ),
    ]
