# Generated by Django 4.2.29 on 2026-03-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creations')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last modification')),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='gym.gymtenant')),
            ],
            options={
                'verbose_name_plural': 'Gym Parameters',
            },
        ),
    ]
